#file: noinspection SpringBootApplicationYaml
server:
  port: 8080

logging:
  level:
    com.example: debug
    org.springframework.web.reactive.function.client: trace

kudago:
  max-retries: 3
  retry-delay: 3000
  base-url: https://kudago.com/public-api/v1.4

currency-service:
  base-url: http://localhost:8081/api/v1/currencies

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_CONTAINER_NAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  profiles:
    active: prod

data-loading:
  threads: 2
  interval: 3600 # in seconds

