#file: noinspection SpringBootApplicationYaml
server:
  port: 8080

logging:
  level:
    com.example: debug

kudago:
  max-retries: 3
  retry-delay: 3000
  base-url: https://kudago.com/public-api/v1.4

spring:
  profiles:
    active: prod

data-loading:
  threads: 2
  interval: 3600 # in seconds
