include:
  - compose-network.yml
  - compose-logging.yml
  - compose-metrics.yml

services:
  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - kudago-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
    networks:
      - app-tier

  migration:
    image: liquibase:4.29.2
    container_name: liquibase
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    command: [
      "--url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}",
      "--username=${POSTGRES_USER}",
      "--password=${POSTGRES_PASSWORD}",
      "--search-path=/liquibase/changelog/",
      "--driver=org.postgresql.Driver",
      "--changeLogFile=db-changelog.yaml",
      "update"
    ]
    volumes:
      - ../migrations/db/changelog:/liquibase/changelog/
    networks:
      - app-tier

volumes:
  kudago-db:
    name: kudago-db
    driver: local