include:
  - compose-environment.yml
  - compose-network.yml
  - compose-logging.yml

services:
  kudago-service:
    build:
      context: ../
      dockerfile: docker/kudago-service.Dockerfile
    container_name: kudago-service
    networks:
      - app-tier
    restart: unless-stopped
    env_file: .env
    ports:
      - '8080:8080'
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: postgres
    depends_on:
      migration:
        condition: service_completed_successfully
